echo  '*Test Date:*'
echo  '*Environment:*'
echo  '*Scenario:*'
echo  '*Description:*'
echo  '*Reproduce steps:*'
echo  '*Expected result:*'
echo  '*Actual result:*'
echo  '*Affected Cases*'
echo  '{code}'
echo  '{code}'
